# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Behavioral data science, ML for trading and other pages... 
description: A professional diary...
github_username: ChristoGH
# Set this to true to get LaTeX math equation support
use_math: 

# Set this to true to display the summary of your blog post under your title on the Home page.
show_description: true

# Set this to true to display image previews on home page, if they exist
show_image: false

# Set this to true to turn on annotations with hypothes.is (https://web.hypothes.is/)
annotations: false

# Set this to true to display tags on each post
show_tags: true

# Add your Google Analytics ID here if you have one and want to use it
# google_analytics: UA-57531313-5

exclude:
  - docker-compose.yml
  - action.yml
  - Makefile

# this setting allows you to keep pages organized in the _pages folder
include:
  - _pages

# This specifies what badges are turned on by default for notebook posts.
default_badges:
  github: true
  binder: true
  colab: true

# Escape HTML in post descriptions
html_escape:
  description: false

# Everything below here can be ignored, unless you want to change the theme entirely
future: true
theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-octicons
#   - jekyll-github-metadata
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-toc
  - jekyll-twitter-plugin
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji



titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

# to limit size of xml as it can grow quite large.
feed:
  posts_limit: 5 #default posts_limit: 10
  excerpt_only: true
  
exclude:
  - settings.ini